server:
  port: 8080
  servlet:
    context-path: /user

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/qlth"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: trungquanadg123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  valid-duration: 36000 # in second
  refreshable-duration: 360000 # in seconds

